import { defineConfig, presetWind4, transformerVariantGroup } from 'unocss';

export default defineConfig({
  safelist: ["[&_svg:not([class*='size-'])]:size-3", "[&_svg:not([class*='size-'])]:size-4"],
  shortcuts: {
    'page-shell': 'w-full max-w-[1600px] px-3 sm:px-4 lg:px-6 2xl:px-8',
  },
  presets: [
    presetWind4({
      dark: {
        dark: '.theme-dark',
        light: '.theme-minimal',
      },
      preflights: {
        reset: true,
      },
    }),
  ],
  theme: {
    colors: {
      accent: 'var(--accent)',
      'accent-foreground': 'var(--accent-foreground)',
      background: 'var(--background)',
      border: 'var(--border)',
      card: 'var(--card)',
      'card-foreground': 'var(--card-foreground)',
      destructive: 'var(--destructive)',
      'destructive-foreground': 'var(--destructive-foreground)',
      foreground: 'var(--foreground)',
      input: 'var(--input)',
      muted: 'var(--muted)',
      'muted-foreground': 'var(--muted-foreground)',
      popover: 'var(--popover)',
      'popover-foreground': 'var(--popover-foreground)',
      primary: 'var(--primary)',
      'primary-foreground': 'var(--primary-foreground)',
      ring: 'var(--ring)',
      secondary: 'var(--secondary)',
      'secondary-foreground': 'var(--secondary-foreground)',
      success: 'var(--color-success)',
      warning: 'var(--color-warning)',
      'chart-1': 'var(--chart-1)',
      'chart-2': 'var(--chart-2)',
      'chart-3': 'var(--chart-3)',
      'chart-4': 'var(--chart-4)',
      'chart-5': 'var(--chart-5)',
      sidebar: 'var(--sidebar)',
      'sidebar-accent': 'var(--sidebar-accent)',
      'sidebar-accent-foreground': 'var(--sidebar-accent-foreground)',
      'sidebar-border': 'var(--sidebar-border)',
      'sidebar-foreground': 'var(--sidebar-foreground)',
      'sidebar-primary': 'var(--sidebar-primary)',
      'sidebar-primary-foreground': 'var(--sidebar-primary-foreground)',
      'sidebar-ring': 'var(--sidebar-ring)',
    },
    radius: {
      sm: 'calc(var(--radius) * 0.6)',
      md: 'calc(var(--radius) * 0.8)',
      lg: 'var(--radius)',
      xl: 'calc(var(--radius) * 1.4)',
      '2xl': 'calc(var(--radius) * 1.8)',
      '3xl': 'calc(var(--radius) * 2.2)',
      '4xl': 'calc(var(--radius) * 2.6)',
    },
  },
  transformers: [transformerVariantGroup()],
});
